# main.yml
name: deploy to aliyun
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@master
      # 下载 git submodule
      - uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive
      # 使用 node:10
      - name: use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      # npm install
      - name: npm install and build
        run: |
          npm install
          npm run build
         env:
          CI: true
      # Deploy
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          ARGS: "-avz --delete"
          SOURCE: "build/"
          REMOTE_HOST: ${{ secrets.ftp_sever }}
          REMOTE_USER: ${{ secrets.ftp_username }}
          REMOTE_PASSWORD: ${{ secrets.ftp_password }} 
          TARGET: "./../www/wwwroot/imeeil/"
