/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    /*documentionSidebar: [{ type: 'autogenerated', dirName: 'documention' }],
    exampleSidebar: [{ type: 'autogenerated', dirName: 'example' }],
    learnSidebar: [{ type: 'autogenerated', dirName: 'learn' }],*/
    //documentionSidebar: [{ type: 'autogenerated', dirName: 'documention' }],
    //exampleSidebar: [{type: 'autogenerated', dirName: 'example'}],
    //learnSidebar: [{ type: 'autogenerated', dirName: 'learn' }],

    // But you can create a sidebar manually

    documentionSidebar: [
        {
            type: 'autogenerated',
            //label: '中文文档',
            dirName: 'documentation', // '.' 即当前的文档文件夹
            //items: [],
        },
    ],
    patchesSidebar: [
        {
            type: 'autogenerated',
            // collapsed: false,
            //label: '例子',
            dirName: 'patches', // '.' 即当前的文档文件夹
            //items: [],
            //items: ['hello'],
        },
    ],
    exampleSidebar: [
        {
            type: 'autogenerated',
            dirName: 'example',
        },
    ],
    systemSidebar: [
        {
            type: 'autogenerated',
            dirName: 'system',
        },
    ],
    specialSidebar: [
        {
            type: 'autogenerated',
            dirName: 'special',
        },
    ],
    deviceSidebar: [
        {
            type: 'autogenerated',
            dirName: 'device',
        },
    ],
    researchSidebar: [
        {
            type: 'autogenerated',
            dirName: 'research',
        },
    ],
    shortcutsSidebar: [
        {
            type: 'autogenerated',
            dirName: 'shortcuts',
        },
    ],

    /*mySidebar: [
        //'intro',
        {
            type: 'autogenerated',
            label: '中文文档',
            items: [
                //'tutorial-intro',
                /!*{
                    type: 'autogenerated',
                    dirName: 'tutorials/easy', // 从 docs/tutorials/easy 生成侧边栏切片
                },
                //'tutorial-medium',
                {
                    type: 'autogenerated',
                    dirName: 'tutorials/advanced', // 从 docs/tutorials/hard 生成侧边栏切片
                },*!/
                //'tutorial-end',
            ],
        },
        {
            type: 'autogenerated',
           // label: '例子',
            dirName: 'example', // 从 docs/api 生成侧边栏切片
        },
      /!*  {
            type: 'category',
            label: 'Community',
            items: ['team', 'chat'],
        },*!/
    ],
*/

};

module.exports = sidebars;
