name: Deploy via git-ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: git-ftp push
      uses: sebastianpopp/git-ftp-action@releases/v3
      with:
        url: "ftp://120.79.21.204//www/wwwroot/imeeil"
        user: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        