name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        with:
          FTP_SERVER: ${{ secrets.ftp_host }}
          FTP_USERNAME: ${{ secrets.ftp_user }}
          FTP_PASSWORD: ${{ secrets.ftp_pwd }}
          local-dir: build/
        env:
          CI: true
